version: '3.8'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'pgsql-container'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: .
    image: sending-pix
    container_name: sending-pix-container
    restart: always
    volumes:
      - .:/home/sending-pix
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
